import { randomUUID } from 'node:crypto'
import { mkdir, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

import { assertToolConfig, resolveConfigPath } from './config.js'
import type { OxcTool } from './index.js'

const EDITOR_CONFIG_NAMES: Record<OxcTool, string> = {
  oxlint: '.oxc-bridge.oxlint.generated.mjs',
  oxfmt: '.oxc-bridge.oxfmt.generated.mjs',
}

function proxySource(configPath: string, tool: OxcTool): string {
  return `// Generated by oxc-config-bridge. Do not edit.\nimport config from ${JSON.stringify(pathToFileURL(configPath).href)}\n\nexport default config.${tool}\n`
}

async function writeProxy(configPath: string, tool: OxcTool, proxyPath: string): Promise<void> {
  await assertToolConfig(configPath, tool)
  await writeFile(proxyPath, proxySource(configPath, tool), { encoding: 'utf8', flag: 'wx' })
}

export interface TemporaryProxy {
  path: string
  remove: () => Promise<void>
}

export async function createTemporaryProxy(
  configPath: string,
  tool: OxcTool,
): Promise<TemporaryProxy> {
  const directory = path.dirname(configPath)
  const proxyPath = path.join(directory, `.oxc-bridge.${tool}.${process.pid}.${randomUUID()}.mjs`)
  await writeProxy(configPath, tool, proxyPath)

  return {
    path: proxyPath,
    remove: () => rm(proxyPath, { force: true }),
  }
}

export interface EditorConfigPaths {
  oxlint?: string
  oxfmt?: string
}

export interface EditorConfigOptions {
  configPath?: string
  cwd?: string
  outputDirectory?: string
}

function resolveOutputDirectory(configPath: string, options?: EditorConfigOptions): string {
  if (options?.outputDirectory) {
    return path.resolve(options.cwd ?? process.cwd(), options.outputDirectory)
  }
  return path.dirname(configPath)
}

export async function prepareEditorConfigs(
  options?: EditorConfigOptions,
): Promise<EditorConfigPaths> {
  const configPath = await resolveConfigPath(options?.configPath, options?.cwd)
  const directory = resolveOutputDirectory(configPath, options)
  const paths: EditorConfigPaths = {}
  await mkdir(directory, { recursive: true })

  for (const tool of ['oxlint', 'oxfmt'] as const) {
    const proxyPath = path.join(directory, EDITOR_CONFIG_NAMES[tool])
    await rm(proxyPath, { force: true })
    try {
      await writeProxy(configPath, tool, proxyPath)
      paths[tool] = proxyPath
    } catch (error) {
      if (error instanceof Error && error.message.includes(`does not define an ${tool} section`)) {
        continue
      }
      throw error
    }
  }

  return paths
}

export async function cleanEditorConfigs(options?: EditorConfigOptions): Promise<void> {
  const configPath = await resolveConfigPath(options?.configPath, options?.cwd)
  const directory = resolveOutputDirectory(configPath, options)
  await Promise.all(
    Object.values(EDITOR_CONFIG_NAMES).map((filename) =>
      rm(path.join(directory, filename), { force: true }),
    ),
  )
}
